### ISSUE TITLE
`RationalRoot(...)` of a rational number.

### ISSUE THREAD

**Issue by marcusbritanicus** [Jutho/RationalRoots.jl#6]
I am writing a program which involves adding two `RationalRoot(...)` numbers. The resultant sum can always be expressed as `√(a//b)`. When the resultant sum, `s`, is an irrational number, like `s = 0.6324555320336759`, I can easily do `RationalRoot( s )` to obtain `+√(2//5)`. However, the problem arises when the resultant sum is rational, like, `s = 0.4`. In such case, when I do `RationalRoot( s )`, I get `+√(108766179679893//679788622999331)`.

Is there some way I can consistently convert `s` into a proper `RationalRoot`?

**Comment by Jutho** [comment]
The problem of the strange conversion lies with floating point precision:
```julia
julia> 0.4^2
0.16000000000000003
```
That the other example works so cleanly is probably a coincidence. However, you can use rationals instead:
```julia
julia> s = RationalRoot(4//10)
+√(4//25)
```
Note however that adding two `RationalRoots` will convert back to floating point precision, since the result can generically not be represented as a `RationalRoot`

Maybe you are looking for something like algebraic integers. This package is very simple and has a single goal, namely to represent square roots of rationals exactly (because they appear often, for example, as Clebsch-Gordan coefficients in physics). However, it does not support any complicated symbolic or number-theoretic manipulations.

**Comment by Jutho** [comment]
I think I can close this issue? Feel free to reopen if there are additional questions here.

**Comment by marcusbritanicus** [comment]
@Jutho Thank you. I have no additional questions. I got to know about this package from `WignerSymbols` package. I was attempting to solve a problem that involves Wigner 3j and 6j  symbols.

It took me a little thinking to find a solution for this. Finally, I managed to solve this today. This is what I managed to rig up:

```julia
function getRationalRoot( X )
    function getRationalRoot1( X )
        # Rationalize the fraction
        R = rationalize( X )

        # If X was a surd, the numerator will be a very large number
        # So, we will just return the RationalRoot of X, which will be accurate
        if ( numerator( R ) > 1e6 )
            return RationalRoot( X )

        # Otherwise, X was rational.
        # So, we return the rationalized version of X as RationalRoot
        else
            return RationalRoot( R )

        end
    end

    function getRationalRoot2( X )
        R   = RationalRoot{BigInt}( X )
        Rsq = R ^ 2
        if ( numerator( Rsq ) > 1e6 )
            return RationalRoot( R )

        else
            return RationalRoot( X )

        end
    end

    R1 = getRationalRoot1( X )
    R2 = getRationalRoot2( X )

    if ( numerator( R1 ^ 2 ) < numerator( R2 ^ 2 ) )
        return R1

    end

    return R2
end
```

This might be a rather convoluted approach, but it works perfectly well. I am adding this so that it may help someone else who faces this problem.

**Note:** I was able to use `if ( numerator( Rsq ) > 1e6 )` knowing that my numerator is not going to be larger than 1000.
